module.exports = {
    userFormateError:{
        code:'10001',
        message:'用户名或密码为空',
        resulit:''
    },
    userAlreadyExited:{
        code:'10002',
        message:'用户名已注册',
        resulit:''
    },
    userRegisterError:{
        code:'10003',
        message:'用户名注册错误',
        resulit:''
    },
    userDoesNotExist:{
        code:'10004',
        message:'用户未注册',
        resulit:''
    },
    userLoginError:{
        code:'10005',
        message:'用户登录失败',
        resulit:''
    },
    invalidPassword:{
        code:'10006',
        message:'密码错误',
        resulit:''
    },
    TokenExpiredError:{
        code:'10007',
        message:'token过期',
        resulit:''
    },
    JsonWebTokenError:{
        code:'10008',
        message:'无效token',
        resulit:''
    },
    TokenError:{
        code:'10009',
        message:'token异常',
        resulit:''
    },

    // sort
    sortAddError:{
        code:'10101',
        message:'sort添加失败',
        resulit:''
    },
    sortNoAlreadyExited:{
        code:'10102',
        message:'请输入正确的id',
        resulit:''
    },
    sortFormateError:{
        code:'10103',
        message:'类目名为空',
        resulit:''
    },

     // category
     categoryAddError:{
        code:'10201',
        message:'category添加失败',
        resulit:''
    },
    categoryNoAlreadyExited:{
        code:'10202',
        message:'请输入正确的id',
        resulit:''
    },
    categoryFormateError:{
        code:'10203',
        message:'目录名为空',
        resulit:''
    },
    // tag
   categoryAddError:{
       code:'10301',
       message:'tag添加失败',
       resulit:''
   },
   categoryNoAlreadyExited:{
       code:'10302',
       message:'请输入正确的id',
       resulit:''
   },
   categoryFormateError:{
       code:'10303',
       message:'标签名为空',
       resulit:''
   },
}